### ISSUE TITLE
does this support scss?

### ISSUE THREAD

**Issue by craigcosmo** [ecmel/vscode-html-css#135]
```js
import './signup.scss'
export default class Signup extends React.Component {
	render() {
		return (
			<div className="signupComponent">
			</div>
		)
	}
}
```
**signup.scss**
```css
.signupComponent {
	.form {
		font-size: 12px;
	}
}

```

When I type `className="si` not happen, no autocomplete
