### ISSUE TITLE
Doesn't seem to support dynamically generated class names?

### ISSUE THREAD

**Issue by dragon8github** [ecmel/vscode-html-css#164]
```scss
// .fz-1 ~ .fz-60
@for $i from 0 through 60 {
  .fz-#{$i} {
    font-size: $i * 0.1em !important;
  }
}
```

The plugin is powerful, but it's a shame it's not supported.

Am I missing a configuration?
