### ISSUE TITLE
doesn`t support the Interpolation grammer and the '@root' tag in scss.

### ISSUE THREAD

**Issue by man-fish** [ecmel/vscode-html-css#167]
index.scss
```scss
.m-header {
    display: flex;
    flex-direction: row;
    justify-content: space-between;
    align-items: center;
    width: 100%;
    @at-root #{&}__logo {
        width: 20%;
        height: 50px;
    }

    @at-root #{&}__search-bar {
        width: 60%;
        height: 50px;
    }
}
```
App.js
```js
        <div className="App">
            <div className="m-header">  // works well
                <div className="m-header__logo"></div>  // nothing happened
                <div className="m-header__search-bar"></div>
            </div>
        </div>
```
