### ISSUE TITLE
Escape character breaking css intellisense 

### ISSUE THREAD

**Issue by jess-mann** [ecmel/vscode-html-css#171]
```css
.\+pd-all-lg {
	padding: 64px!important;
}
.\+pd-all-md {
	padding: 32px!important;
}
.\+pd-all-sm {
	padding: 7.999px!important;
}
.\+pd-all-none {
	padding: 0!important;
}
```

Extension not able to do class completion when classes contain escape character.
