### ISSUE TITLE
Property Tag is not supported

### ISSUE THREAD

**Issue by fschatbot** [ecmel/vscode-html-css#245]
**Context**: https://developer.mozilla.org/en-US/docs/Web/CSS/@property

Putting in sometime as simple as
```css
@property --color {
	syntax: "<color>";
	inherits: false;
	initial-value: #000;
}
```
makes the coloring go haywire and throw lots and lots of errors
